[package]
name = "presenter"
version = "0.1.5"
authors = ["nhuthm080820 <nhuthm080820@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domain = { path = "../domain" }
