name: Build and Push

on:
  push:
    branches:
      - development
      - prod

jobs:
  check_lambda_files:
    name: Check Lambda source code
    outputs:
      run_job: ${{ steps.check_lambda_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check modified AWS Lambda Source Code
        id: check_lambda_files
        working-directory: student-lambda
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file == student-lambda/terraform/* || $file == .github/*  ]]; then
              echo "This modified file is not Lambda source code"
              echo "::set-output name=run_job::false"
              break
            else
              echo "::set-output name=run_job::true"
            fi
          done < files.txt

  codestyle:
    runs-on: ubuntu-latest
    needs: [ check_lambda_files ]
    if: needs.check_lambda_files.outputs.run_job == 'true'
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt
      - uses: actions/checkout@v2
      -
        working-directory: student-app
        run: cargo fmt --all -- --check
      -
        working-directory: student-lambda
        run: cargo fmt --all -- --check
  lint:
    runs-on: ubuntu-latest
    needs: [ check_lambda_files ]
    if: needs.check_lambda_files.outputs.run_job == 'true'
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
      - uses: actions/checkout@v2
      - 
        working-directory: student-lambda
        run: cargo clippy --all-targets -- -D clippy::all
      -
        working-directory: student-app
        run: cargo clippy --all-targets -- -D clippy::all
  compile:
    runs-on: ubuntu-latest
    needs: [ check_lambda_files ]
    if: needs.check_lambda_files.outputs.run_job == 'true'
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@v2
      - 
        working-directory: student-lambda
        run: cargo check --all
      -
        working-directory: student-app
        run: cargo check --all
  # deploy on pushes to master branch
  # assumes aws credentials (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY) are set in github secrets
  push_dev:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    env:
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
    steps:
      - name: App Deploy Terraform Config
        run: |
          chmod +x ./scripts/terraform-enterprise-push.sh
          ./scripts/terraform-enterprise-push.sh student-lambda/terraform HocVienCongGiao/dev-sg-lambda-services-hvcg-student-service
  push_prod:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    env:
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}

    needs: [test]
    steps:
      - name: Install Musl-gcc
        run: |
          sudo apt update -y
          sudo apt install -y musl-tools

      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
        with:
          targets: x86_64-unknown-linux-musl

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Build and Push for Prod
        working-directory: student-lambda
        # From line 197 to line 216 is for fixing open ssl issue
        run: |
          sudo apt install -y pkg-config libssl-dev
          sudo ln -s /usr/include/x86_64-linux-gnu/asm /usr/include/x86_64-linux-musl/asm
          sudo ln -s /usr/include/asm-generic /usr/include/x86_64-linux-musl/asm-generic
          sudo ln -s /usr/include/linux /usr/include/x86_64-linux-musl/linux
          sudo mkdir /musl
          sudo apt-get install wget
          sudo wget https://github.com/openssl/openssl/archive/OpenSSL_1_1_1f.tar.gz
          sudo tar zxvf OpenSSL_1_1_1f.tar.gz
          cd openssl-OpenSSL_1_1_1f/
          echo nhut3
          sudo CC="musl-gcc -fPIE -pie" ./Configure no-shared no-async --prefix=/musl --openssldir=/musl/ssl linux-x86_64
          sudo apt-get install build-essential
          sudo make depend
          sudo make -j$(nproc)
          sudo make install
          export PKG_CONFIG_ALLOW_CROSS=1
          export OPENSSL_STATIC=true
          export OPENSSL_DIR=/musl
          cd /home/runner/work/student-service/student-service/student-lambda
          cargo clean
          cargo build --release --target x86_64-unknown-linux-musl
          cp ./target/x86_64-unknown-linux-musl/release/student ./bootstrap && zip student.zip bootstrap

          aws s3 cp ./student.zip s3://891616054205-ap-southeast-1-aws-lambda/prod-sg-hocvienconggiao/${{ github.event.repository.name }}/latest/student.zip

