name: Run Lint on Ubuntu

on:
  push:
    branches-ignore:
      - master
      
jobs:
  codestyle-lint-compile:
    runs-on: ubuntu-latest
    steps:
#       - name: Set up Rust
#         uses: hecrj/setup-rust-action@v1
#         with:
#           components: rustfmt
      - uses: actions/checkout@v2
      - name: Cargo version
        working-directory: student-lambda      
        run: |
          source $HOME/.cargo/env
          cargo version
      - name: Lambda Cargo fmt
        working-directory: student-lambda
        run: |
          source $HOME/.cargo/env
          cargo fmt --all -- --check
      - name: Check App Cargo fmt
        working-directory: student-app
        run: |
          source $HOME/.cargo/env
          cargo fmt --all -- --check
          
      - name: Lambda Cargo lint
        working-directory: student-lambda
        run: |
          source $HOME/.cargo/env
          cargo clippy --all-targets -- -D clippy::all
      - name: App Cargo lint
        working-directory: student-app
        run: |
          source $HOME/.cargo/env
          cargo clippy --all-targets -- -D clippy::all

      - name: Lambda Cargo check for compile
        working-directory: student-lambda
        run: |
          source $HOME/.cargo/env
          cargo check --all
      - name: App Cargo check for compile
        working-directory: student-app
        run: |
          source $HOME/.cargo/env
          cargo check --all
